name: Render Deploy Frontend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.3.0
      with:
        service_id: ${{ secrets.FRONTEND_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        clear_cache: false
        wait_deploy: true